server:
  port: 8081

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
